name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-15"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDA5MWM1ODAtODgyOS00MTQzLTk5MmMtMGNhYjZjOGZlMGQxIiwidGVuYW50X2lkIjoiODQ1YTQ2YTFlZGNlN2M5ZjlkYTYzOTY4Mjg3ZTdlODY2Njc1NzhjYzBiNjRjMjU0ZjA4YWZmNzkyNWMxZjdiNCIsImludGVybmFsX3NlY3JldCI6ImEwNTQxOTlhLTE0YzUtNDVmMy1iY2UxLTUzNWZhZTk1ZmVmYSJ9.yHFmuZ9RSQ42xI9WGhMEKIsea8544Nf-AybgDM-ew7I"

JWT_SECRET="your secret"